on:
  push:
    branches:
      - main
name: 🖥️ Enviado a "producción"
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server:     ftpupload.net
        username:   epiz_31597846
        password:   ${{ FTP_PASSWORD }}
        server-dir: /htdocs
